version: '2'
services:
    recipeapplication-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/jhipster/RecipeApplication/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=RecipeApplication
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
